# Generated by Django 5.0.6 on 2024-05-24 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patient', '0001_initial'),
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.BigIntegerField()),
                ('admission_date', models.DateTimeField(auto_now=True)),
                ('max_quantity', models.IntegerField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.staff')),
            ],
        ),
    ]
