# Generated by Django 5.0.6 on 2024-05-24 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_fname', models.CharField(max_length=15)),
                ('patient_lname', models.CharField(max_length=15)),
                ('patient_phone', models.CharField(max_length=13, unique=True)),
                ('pharmacy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy.pharmacy')),
            ],
        ),
    ]
