# Generated by Django 5.0.6 on 2024-05-24 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_fname', models.CharField(max_length=15)),
                ('staff_lname', models.CharField(max_length=15)),
                ('staff_address', models.CharField(max_length=15)),
                ('staff_phone', models.CharField(max_length=13)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.department')),
            ],
        ),
    ]
