# Generated by Django 5.0.6 on 2024-05-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(max_length=15)),
                ('pharmacy_address', models.CharField(max_length=15)),
                ('pharmacy_phone', models.CharField(max_length=13)),
            ],
        ),
    ]
